stages:
  - deploy

deploy:
  image: alpine:latest
  stage: deploy
  tags:
    - avis
  script:
    - apk update && apk add openssh-client
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$ID_RSA")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh -p 9443 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /home/nft/nft-marketplace-workspace && git stash && git pull && npm i && pm2 restart  serve-admin serve-customer" 
  only:
    - avis_dev